<?php
namespace Versionable\Tests\Common\Collection;

use Versionable\Common\Collection\ArrayList;

/**
 * Test class for ArrayList.
 * Generated by PHPUnit on 2011-01-10 at 17:39:44.
 */
class ArrayListTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSet().
     */
    public function testSet()
    {
      $one = new \stdClass();
      $one->name = 'one';
      
      $two = new \stdClass();
      $two->name = 'two';
      
      $this->object->add($one);
      $this->object->set(0, $two);

      $elements = $this->readAttribute($this->object, 'elements');

      $this->assertEquals($two, $elements[0]);
    }

    public function testSetOutOfBounds()
    {
      $this->setExpectedException('\\OutOfBoundsException');
      $this->object->set(1, 200);
    }

    /**
     * @todo Implement testAddAt().
     */
    public function testAddAt()
    {
      $object = new \stdClass();
      $object->name = 'one';
      
      $this->object->addAt(0, $object);

      $elements = $this->readAttribute($this->object, 'elements');
      $this->assertEquals($object, $elements[0]);
    }

    public function testAddAtFail()
    {
      $this->setExpectedException('\OutOfBoundsException');
      
      $this->object->addAt(1, new \stdClass());
    }
    
    public function testAddAtAll()
    {
      //$this->
    }
}
