<?php
namespace Versionable\Tests\Common\Collection;

use Versionable\Common\Collection\ArrayList;

/**
 * Test class for ArrayList.
 * Generated by PHPUnit on 2011-01-10 at 17:39:44.
 */
class ArrayListTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSet().
     */
    public function testSet()
    {
      $this->object->add(100);
      $this->object->set(0, 200);

      $elements = $this->readAttribute($this->object, 'elements');

      $this->assertEquals(200, $elements[0]);
    }

    public function testSetOutOfBounds()
    {
      $this->setExpectedException('\\OutOfBoundsException');
      $this->object->set(1, 200);
    }

    /**
     * @todo Implement testAddAt().
     */
    public function testAddAt()
    {
      $this->object->addAt(0, 100);

      $elements = $this->readAttribute($this->object, 'elements');
      $this->assertEquals(100, $elements[0]);
    }

    public function testAddAtFail()
    {
      $this->setExpectedException('\OutOfBoundsException');

      $this->object->addAt(1, 100);
    }
}
