<?php
namespace Versionable\Tests\Common\Collection;

use Versionable\Common\Collection\ArrayList;
use Versionable\Common\Collection\MockComparableItem as Element;

/**
 * Test class for ArrayList.
 * Generated by PHPUnit on 2011-01-10 at 17:39:44.
 */
class ArrayListTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayList
     */
    protected $object;
    
    protected $elements = array();

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {     
        $this->elements['alpha'] = new Element('alpha');
        $this->elements['bravo'] = new Element('bravo');
        $this->elements['charlie'] = new Element('charlie');
        $this->elements['delta'] = new Element('delta');
        $this->elements['echo'] = new Element('echo');        
        
        $this->object = new ArrayList(array_values($this->elements));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testRemoveRange()
    {
     
      $expected = array($this->elements['alpha'], $this->elements['bravo'], $this->elements['echo']);
      
      $this->object->removeRange(2, 4);
      
      $this->assertEquals($expected, $this->readAttribute($this->object, 'elements')); 
    }
    
    public function testRangeRemoveOutofBounds()
    {
      $this->setExpectedException('\OutOfBoundsException');
      
      $this->object->removeRange(0, 100);
    }
    
    public function testRangeRemoveBadRange()
    {
      $this->setExpectedException('\OutOfBoundsException');
      
      $this->object->removeRange(4, 0);
    }
}
